[package]
name = "rust-plotters-example"
version = "0.1.0"
authors = ["Borys Minaiev <bminaiev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

druid = "*"